import path from "path";
/**
 * HTML Generator for Glim YouTube Summaries
 *
 * Generates a well-formatted HTML document containing the video summary
 * with support for multiple languages and RTL text direction.
 *
 * @param {string} title - The title of the YouTube video
 * @param {string} imageUrl - URL to the video thumbnail image
 * @param {Array} sections - Array of sections with topics and questions/answers
 * @param {string} lang - Language code (default: 'en')
 * @returns {string} Complete HTML document as a string
 */
export function htmlGenerator(title, imageUrl, sections, lang = "en") {
    const isRTL = ["ar", "he", "fa", "ur"].includes(lang);

    // Localized footer text
    const localizedGeneratedBy = {
        en: "Generated by",
        fr: "Généré par",
        ar: "تم الإنشاء بواسطة",
        es: "Generado por",
        de: "Erstellt von",
    };

    const generatedByText =
        localizedGeneratedBy[lang] || localizedGeneratedBy["en"];

    let html = `<!DOCTYPE html>
<html lang="${lang}" dir="${isRTL ? "rtl" : "ltr"}">
<head>
  <link rel="icon" href="${path.resolve(path.join(process.cwd(), "./assets/logo.jpeg"))}" type="image/x-icon" />
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Glim</title>
  <link rel="stylesheet" href="https://unpkg.com/tailwindcss@2.2.19/dist/tailwind.min.css" />
  <link href="https://fonts.googleapis.com/css2?family=Patrick+Hand&display=swap" rel="stylesheet" />
  <style>
    body { 
      background-color: #f7fafc; 
      font-family: ${isRTL ? "'Amiri', serif" : "'Patrick Hand', sans-serif"};
      direction: ${isRTL ? "rtl" : "ltr"};
      text-align: ${isRTL ? "right" : "left"};
    }
    h1, h2 { font-weight: 700; margin-bottom: 0.5rem; }
    ul { list-style-type: disc; ${isRTL ? "margin-right: 1.5rem;" : "margin-left: 1.5rem;"} margin-bottom: 1.5rem; }
    li { margin-bottom: 1rem; }
    ol { list-style-type: decimal; ${isRTL ? "margin-right: 2rem;" : "margin-left: 2rem;"}; margin-top: 0.5rem; }
    ol li { margin-bottom: 0.2rem; }
    .bullet-content ol { margin-top: 0.3rem; margin-bottom: 0.3rem; }
    .footer { text-align: center; margin-top: 2rem; font-size: 0.9rem; color: #718096; }
  </style>
</head>
<body class="min-h-screen flex items-center justify-center p-4">
  <div class="max-w-2xl w-full bg-white rounded-2xl shadow-lg p-6">
    <div class="mb-6 ${isRTL ? "text-left" : "text-right"} text-gray-500 text-sm">
      ${generatedByText} <a href="https://github.com/Hassan-ach/vist" class="underline hover:text-gray-700">Bagi</a>
    </div>
    <h1 class="text-4xl text-gray-800 mb-4">${title}</h1>
    <img src="${imageUrl}" alt="Video thumbnail" class="rounded-xl mb-6" />`;

    for (const section of sections) {
        html += `<h2 class="text-2xl text-gray-800 mb-4">${section.title}</h2>
    <ul class="text-gray-600">`;
        for (const [bold, text] of section.bullets) {
            html += `<li><strong>${bold}</strong><br /><div class="bullet-content">${text}</div></li>`;
        }
        html += "</ul>";
    }

    html += `
    <div class="footer">
      <hr class="my-6 border-gray-200" />
      <p class="text-center">Made with ❤️ by Bagi</p>
    </div>
  </div>
</body>
</html>`;
    return html;
}
