/**
 * =============================================================================
 * Glim: YouTube Summary HTML Generator
 *
 * This module provides a flexible system for generating themed HTML documents
 * for YouTube video summaries. It supports multiple languages, RTL text, and
 * a variety of visual themes.
 *
 * Main Principles:
 * 1. DRY (Don't Repeat Yourself): A single core generator function builds the
 *    HTML using theme-specific configuration.
 * 2. Thematic Abstraction: Each visual theme (Neomorphism, Hacker, etc.) is
 *    defined as a configuration object, separating style from structure.
 * 3. Scalability: Adding a new theme requires only adding a new configuration
 *    object, not duplicating the entire generator logic.
 *
 * @see _generateHtmlForTheme - The core private generator function.
 * @see THEMES - The configuration object for all supported themes.
 * =============================================================================
 */

// --- UTILITY HELPERS ---------------------------------------------------------

const localizedGeneratedBy = {
    en: "Generated by",
    fr: "Généré par",
    ar: "تم الإنشاء بواسطة",
    es: "Generado por",
    de: "Erstellt von",
};

/**
 * Checks if a language code corresponds to a right-to-left language.
 * @param {string} lang - The language code (e.g., 'en', 'ar').
 * @returns {boolean} True if the language is RTL.
 */
function _isRTL(lang) {
    return ["ar", "he", "fa", "ur"].includes(lang);
}

/**
 * Retrieves the localized "Generated by" text.
 * @param {string} lang - The language code.
 * @returns {string} The localized text.
 */
function _getGeneratedByText(lang) {
    return localizedGeneratedBy[lang] || localizedGeneratedBy["en"];
}

// --- CORE HTML GENERATION LOGIC ----------------------------------------------

/**
 * The core generator function. It constructs the complete HTML document
 * based on the provided data and a theme configuration.
 * @private
 */
export function _generateHtmlForTheme(
    themeName,
    title,
    imageUrl,
    sections,
    lang,
) {
    const theme = THEMES[themeName];
    if (!theme) {
        throw new Error(`Theme "${themeName}" not found.`);
    }

    const isRTL = _isRTL(lang);
    const generatedByText = _getGeneratedByText(lang);

    // 1. Build the HTML for the summary sections by iterating through the data
    let sectionsHtml = sections
        .map((section) => {
            const bulletsHtml = section.bullets
                .map(([bold, text]) => theme.templates.bulletItem(bold, text))
                .join("\n");

            const bulletListHtml = theme.templates.bulletList(bulletsHtml);
            const sectionTitleHtml = theme.templates.sectionTitle(
                section.title,
            );

            return theme.templates.sectionContainer(
                sectionTitleHtml,
                bulletListHtml,
            );
        })
        .join("\n");

    // 2. Assemble the full content for the <body> tag
    const bodyInnerHtml = [
        theme.templates.header(generatedByText, isRTL),
        theme.templates.title(title),
        theme.templates.image(imageUrl),
        theme.templates.extraContent || "",
        sectionsHtml,
        theme.templates.footer(),
    ].join("\n");

    // 3. Construct the full <body> tag with its specific wrapper/container
    const bodyHtml = `
<body class="${theme.bodyClass}">
  ${theme.templates.bodyWrapper(bodyInnerHtml)}
</body>`;

    // 4. Construct the <head> tag
    const headHtml = `
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="icon" href="/assets/logo.jpeg" type="image/x-icon" />
  <title>${theme.pageTitle(title)}</title>
  ${theme.useTailwind ? `<link rel="stylesheet" href="https://unpkg.com/tailwindcss@2.2.19/dist/tailwind.min.css" />` : ""}
  ${theme.fonts}
  <style>
    ${theme.styles(isRTL)}
  </style>
</head>`;

    // 5. Assemble the final HTML document
    return `<!DOCTYPE html>
<html lang="${lang}" dir="${isRTL ? "rtl" : "ltr"}">
${headHtml}
${bodyHtml}
</html>`;
}

// --- THEME CONFIGURATIONS ----------------------------------------------------

const THEMES = {
    default: {
        pageTitle: (title) => `Glim: ${title}`,
        useTailwind: true,
        fonts: `<link href="https://fonts.googleapis.com/css2?family=Patrick+Hand&display=swap" rel="stylesheet" />`,
        bodyClass: "min-h-screen flex items-center justify-center p-4",
        styles: (isRTL) => `
            body { background-color: #f7fafc; font-family: ${isRTL ? "'Amiri', serif" : "'Patrick Hand', sans-serif"}; direction: ${isRTL ? "rtl" : "ltr"}; text-align: ${isRTL ? "right" : "left"}; }
            h1, h2 { font-weight: 700; margin-bottom: 0.5rem; }
            ul { list-style-type: disc; ${isRTL ? "margin-right: 1.5rem;" : "margin-left: 1.5rem;"} margin-bottom: 1.5rem; }
            li { margin-bottom: 1rem; }
            ol { list-style-type: decimal; ${isRTL ? "margin-right: 2rem;" : "margin-left: 2rem;"}; margin-top: 0.5rem; }
            ol li { margin-bottom: 0.2rem; }
            .bullet-content ol { margin-top: 0.3rem; margin-bottom: 0.3rem; }
            .footer { text-align: center; margin-top: 2rem; font-size: 0.9rem; color: #718096; }
            .image-container { margin-bottom: 1.5rem; position: relative; overflow: hidden; border-radius: 0.75rem; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1); transition: transform 0.3s ease, box-shadow 0.3s ease; }
            .image-container:hover { transform: translateY(-2px); box-shadow: 0 6px 12px rgba(0, 0, 0, 0.15); }
            .image-container img { border-radius: 0.75rem; width: 100%; display: block; }
            @media (max-width: 768px) { body { padding: 0.5rem; } .max-w-2xl { padding: 1rem; } }
            @media print { 
                body { background: #ffffff; }
                .max-w-2xl { box-shadow: none; max-width: 100%; padding: 0; }
                .image-container { box-shadow: none; page-break-inside: avoid; }
                .footer { page-break-inside: avoid; }
                h2 { page-break-after: avoid; }
                li { page-break-inside: avoid; }
            }
            /* Accessibility improvements */
            :focus { outline: 3px solid #4299e1; outline-offset: 2px; }
            a:focus { text-decoration: underline; }
        `,
        templates: {
            bodyWrapper: (content) =>
                `<div class="max-w-2xl w-full bg-white rounded-2xl shadow-lg p-6">${content}</div>`,
            header: (text, isRTL) =>
                `<div class="mb-6 ${isRTL ? "text-left" : "text-right"} text-gray-500 text-sm">${text} <a href="https://github.com/Hassan-ach" class="underline hover:text-gray-700">Bagi</a></div>`,
            title: (title) =>
                `<h1 class="text-4xl text-gray-800 mb-4">${title}</h1>`,
            image: (url) =>
                `<div class="image-container"><img src="${url}" alt="Video thumbnail" /></div>`,
            sectionContainer: (title, list) => `<div>${title}${list}</div>`,
            sectionTitle: (title) =>
                `<h2 class="text-2xl text-gray-800 mb-4">${title}</h2>`,
            bulletList: (items) => `<ul class="text-gray-600">${items}</ul>`,
            bulletItem: (bold, text) =>
                `<li><strong>${bold}</strong><br /><div class="bullet-content">${text}</div></li>`,
            footer: () =>
                `<div class="footer"><hr class="my-6 border-gray-200" /><p>Made with ❤️ by Bagi</p></div>`,
        },
    },
    neomorphism: {
        pageTitle: (title) => `Glim: ${title}`,
        useTailwind: true,
        fonts: `<link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@400;500;700&display=swap" rel="stylesheet" />`,
        bodyClass: "min-h-screen flex items-center justify-center p-4",
        styles: (isRTL) => `
            :root { --bg-color: #e6e7ee; --shadow-light: #ffffff; --shadow-dark: #b8b9be; --text-color: #31344b; }
            body { background-color: var(--bg-color); font-family: ${isRTL ? "'Amiri', serif" : "'Quicksand', sans-serif"}; direction: ${isRTL ? "rtl" : "ltr"}; text-align: ${isRTL ? "right" : "left"}; color: var(--text-color); }
            .max-w-2xl { background: var(--bg-color); box-shadow: 6px 6px 12px var(--shadow-dark), -6px -6px 12px var(--shadow-light); }
            h1, h2 { font-weight: 700; margin-bottom: 0.5rem; color: var(--text-color); }
            ul { list-style-type: disc; ${isRTL ? "margin-right: 1.5rem;" : "margin-left: 1.5rem;"} margin-bottom: 1.5rem; }
            li { margin-bottom: 1rem; }
            ol { list-style-type: decimal; ${isRTL ? "margin-right: 2rem;" : "margin-left: 2rem;"}; margin-top: 0.5rem; }
            ol li { margin-bottom: 0.2rem; }
            .bullet-content ol { margin-top: 0.3rem; margin-bottom: 0.3rem; }
            .footer { text-align: center; margin-top: 2rem; font-size: 0.9rem; color: #718096; }
            .text-gray-500 { color: var(--text-color); opacity: 0.7; }
            .text-gray-600 { color: var(--text-color); opacity: 0.8; }
            .text-gray-800 { color: var(--text-color); }
            .rounded-xl { border-radius: 1rem; }
            .rounded-2xl { border-radius: 1rem; }
            .image-container { margin-bottom: 1.5rem; box-shadow: 3px 3px 6px var(--shadow-dark), -3px -3px 6px var(--shadow-light); padding: 0.5rem; border-radius: 1rem; }
            .image-container img { border-radius: 0.5rem; width: 100%; }
            @media (max-width: 768px) { body { padding: 0.5rem; } }
        `,
        templates: {
            bodyWrapper: (content) =>
                `<div class="max-w-2xl w-full bg-white rounded-2xl shadow-lg p-6">${content}</div>`,
            header: (text, isRTL) =>
                `<div class="mb-6 ${isRTL ? "text-left" : "text-right"} text-gray-500 text-sm">${text} <a href="https://github.com/Hassan-ach" class="underline hover:text-gray-700">Bagi</a></div>`,
            title: (title) =>
                `<h1 class="text-4xl text-gray-800 mb-4">${title}</h1>`,
            image: (url) =>
                `<div class="image-container"><img src="${url}" alt="Video thumbnail" /></div>`,
            sectionContainer: (title, list) => `<div>${title}${list}</div>`,
            sectionTitle: (title) =>
                `<h2 class="text-2xl text-gray-800 mb-4">${title}</h2>`,
            bulletList: (items) => `<ul class="text-gray-600">${items}</ul>`,
            bulletItem: (bold, text) =>
                `<li><strong>${bold}</strong><br /><div class="bullet-content">${text}</div></li>`,
            footer: () =>
                `<div class="footer"><hr class="my-6 border-gray-200" /><p>Made with ❤️ by Bagi</p></div>`,
        },
    },
    glassmorphism: {
        pageTitle: (title) => `Glim: ${title}`,
        useTailwind: true,
        fonts: `<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&display=swap" rel="stylesheet" />`,
        bodyClass: "min-h-screen flex items-center justify-center p-4",
        styles: (isRTL) => `
            body { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); background-attachment: fixed; background-size: cover; font-family: ${isRTL ? "'Amiri', serif" : "'Poppins', sans-serif"}; direction: ${isRTL ? "rtl" : "ltr"}; text-align: ${isRTL ? "right" : "left"}; min-height: 100vh; padding: 20px; }
            .max-w-2xl { background: rgba(255, 255, 255, 0.25); backdrop-filter: blur(10px); -webkit-backdrop-filter: blur(10px); border: 1px solid rgba(255, 255, 255, 0.3); border-radius: 20px; box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.37); }
            h1, h2 { font-weight: 600; margin-bottom: 0.5rem; }
            ul { list-style-type: disc; ${isRTL ? "margin-right: 1.5rem;" : "margin-left: 1.5rem;"} margin-bottom: 1.5rem; }
            li { margin-bottom: 1rem; background: rgba(255, 255, 255, 0.1); padding: 15px; border-radius: 10px; }
            ol { list-style-type: decimal; ${isRTL ? "margin-right: 2rem;" : "margin-left: 2rem;"}; margin-top: 0.5rem; }
            ol li { margin-bottom: 0.2rem; background: none; padding: 2px 0; }
            .bullet-content ol { margin-top: 0.3rem; margin-bottom: 0.3rem; }
            .footer { text-align: center; margin-top: 2rem; font-size: 0.9rem; }
            .text-gray-500, .text-gray-600 { color: rgba(255,255,255,0.85); } /* Improved contrast */
            .text-gray-800 { color: white; text-shadow: 0 2px 4px rgba(0,0,0,0.1); }
            .rounded-xl, .rounded-2xl { border-radius: 10px; }
            strong { color: white; font-weight: 600; text-shadow: 0 1px 3px rgba(0,0,0,0.2); }
            a { color: #fff; text-decoration: underline; transition: all 0.3s; }
            a:hover { color: white; text-shadow: 0 0 8px rgba(255,255,255,0.5); }
            a:focus { outline: 2px solid white; outline-offset: 2px; text-decoration: none; } /* Accessibility improvement */
            .border-gray-200 { border-color: rgba(255,255,255,0.3); }
            .image-container { position: relative; margin-bottom: 1.5rem; border-radius: 10px; overflow: hidden; box-shadow: 0 4px 15px 0 rgba(31, 38, 135, 0.37); backdrop-filter: blur(4px); -webkit-backdrop-filter: blur(4px); border: 1px solid rgba(255, 255, 255, 0.18); transition: all 0.3s ease; }
            .image-container:hover { transform: translateY(-5px); box-shadow: 0 8px 25px 0 rgba(31, 38, 135, 0.5); }
            .image-container img { width: 100%; display: block; transition: transform 0.3s; }
            .image-container:hover img { transform: scale(1.03); }
            /* Animated gradient border on hover */
            .image-container::before { content: ''; position: absolute; top: -2px; left: -2px; right: -2px; bottom: -2px; background: linear-gradient(45deg, #667eea, #764ba2, #667eea); background-size: 200% 200%; z-index: -1; border-radius: 12px; opacity: 0; transition: opacity 0.3s ease; animation: gradientMove 3s ease infinite; }
            .image-container:hover::before { opacity: 1; }
            @keyframes gradientMove { 0% { background-position: 0% 50%; } 50% { background-position: 100% 50%; } 100% { background-position: 0% 50%; } }
            @media (max-width: 768px) { body { padding: 10px; } .max-w-2xl { padding: 15px; } }
            @media print { 
                body { background: white; }
                .max-w-2xl { background: white; box-shadow: none; backdrop-filter: none; -webkit-backdrop-filter: none; border: none; }
                .text-gray-500, .text-gray-600, .text-gray-800, strong { color: black !important; text-shadow: none; }
                .image-container { box-shadow: none; border: 1px solid #ddd; }
                .image-container::before { display: none; }
                li { background: none; border: 1px solid #eee; }
            }
        `,
        templates: {
            bodyWrapper: (content) =>
                `<div class="max-w-2xl w-full bg-white rounded-2xl shadow-lg p-6">${content}</div>`,
            header: (text, isRTL) =>
                `<div class="mb-6 ${isRTL ? "text-left" : "text-right"} text-gray-500 text-sm">${text} <a href="https://github.com/Hassan-ach" class="underline hover:text-gray-700">Bagi</a></div>`,
            title: (title) =>
                `<h1 class="text-4xl text-gray-800 mb-4">${title}</h1>`,
            image: (url) =>
                `<div class="image-container"><img src="${url}" alt="Video thumbnail" /></div>`,
            sectionContainer: (title, list) => `<div>${title}${list}</div>`,
            sectionTitle: (title) =>
                `<h2 class="text-2xl text-gray-800 mb-4">${title}</h2>`,
            bulletList: (items) => `<ul class="text-gray-600">${items}</ul>`,
            bulletItem: (bold, text) =>
                `<li><strong>${bold}</strong><br /><div class="bullet-content">${text}</div></li>`,
            footer: () =>
                `<div class="footer"><hr class="my-6 border-gray-200" /><p>Made with ❤️ by Bagi</p></div>`,
        },
    },
    retroY2K: {
        pageTitle: (title) => `Glim: ${title}`,
        useTailwind: true,
        fonts: `<link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&family=VT323&display=swap" rel="stylesheet" />`,
        bodyClass: "min-h-screen flex items-center justify-center p-4",
        extraContent: `
            <div class="retro-decorations">
                <img src="https://media.giphy.com/media/3o7aD2saalBwwftBIY/giphy.gif" alt="Decorative GIF" class="gif gif-1" /> 
                <img src="https://media.giphy.com/media/l41lZnIIqsxKyY6GI/giphy.gif" alt="Decorative GIF" class="gif gif-2" />
                <marquee scrollamount="3" class="marquee">★★★ Welcome to Glim Video Summary ★★★ Made with Y2K vibes by Bagi ★★★</marquee>
            </div>
        `,
        styles: (isRTL) => `
            @keyframes float { 0%, 100% { transform: translateY(0px) rotate(0deg); } 50% { transform: translateY(-10px) rotate(5deg); } }
            @keyframes blink { 0%, 100% { opacity: 1; } 50% { opacity: 0.5; } }
            @keyframes rainbow { 0% { color: #ff00cc; } 14% { color: #ff0000; } 28% { color: #ff9900; } 42% { color: #ffff00; } 57% { color: #00ff00; } 71% { color: #0000ff; } 85% { color: #9900ff; } 100% { color: #ff00cc; } }
            body { background: linear-gradient(135deg, #d0e1f9, #fbd3f2, #e6e6e6); font-family: ${isRTL ? "'Amiri', serif" : "'VT323', monospace"}; direction: ${isRTL ? "rtl" : "ltr"}; text-align: ${isRTL ? "right" : "left"}; background-attachment: fixed; font-size: 18px; }
            h1, h2 { font-family: ${isRTL ? "'Amiri', serif" : "'Press Start 2P', cursive"}; color: #0066ff; text-shadow: 1px 1px 0 #f0f, 2px 2px 0 #ccc; }
            .max-w-2xl { border: 6px inset #ccc; border-radius: 6px; box-shadow: 6px 6px 0 #0ff, -6px -6px 0 #f0f; background: #ffffff url("data:image/svg+xml,%3Csvg width='52' height='26' viewBox='0 0 52 26' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%239e9e9e' fill-opacity='0.15'%3E%3Cpath d='M10 10c0-2.21-1.79-4-4-4-3.314 0-6-2.686-6-6h2c0 2.21 1.79 4 4 4 3.314 0 6 2.686 6 6 0 2.21 1.79 4 4 4 3.314 0 6 2.686 6 6 0 2.21 1.79 4 4 4v2c-3.314 0-6-2.686-6-6 0-2.21-1.79-4-4-4-3.314 0-6-2.686-6-6zm25.464-1.95l8.486 8.486-1.414 1.414-8.486-8.486 1.414-1.414z' /%3E%3C/g%3E%3C/g%3E%3C/svg%3E"); position: relative; }
            .max-w-2xl::before { content: ''; position: absolute; top: -12px; left: -12px; right: -12px; height: 25px; background: linear-gradient(90deg, #ff00cc, #00ccff); border: 2px outset #ccc; }
            .retro-decorations { position: relative; margin: 1rem 0; height: 80px; }
            .gif { position: absolute; width: 70px; height: 70px; animation: float 3s ease-in-out infinite; image-rendering: pixelated; }
            .gif-1 { ${isRTL ? "right" : "left"}: -25px; top: 0; animation-delay: 0s; }
            .gif-2 { ${isRTL ? "left" : "right"}: -25px; top: 0; animation-delay: 1.5s; }
            .marquee { position: relative; margin: 10px 0; background: #000000; color: #00ff00; padding: 5px 0; font-family: ${isRTL ? "'Amiri', serif" : "'Press Start 2P', cursive"}; font-size: 10px; white-space: nowrap; }
            ul { list-style-type: disc; ${isRTL ? "margin-right: 1.5rem;" : "margin-left: 1.5rem;"} margin-bottom: 1.5rem; }
            li { margin-bottom: 1.5rem; position: relative; padding: 5px; }
            li::before { content: "▶"; color: #ff00cc; position: absolute; left: -20px; animation: blink 1s infinite; }
            ol { list-style-type: decimal; ${isRTL ? "margin-right: 2rem;" : "margin-left: 2rem;"}; margin-top: 0.5rem; }
            ol li { margin-bottom: 0.2rem; }
            ol li::before { content: ""; }
            .bullet-content ol { margin-top: 0.3rem; margin-bottom: 0.3rem; }
            .footer { text-align: center; margin-top: 2rem; font-size: 0.9rem; color: #ff00cc; animation: rainbow 10s linear infinite; }
            .text-4xl { font-size: 1.8rem; line-height: 1.4; margin-bottom: 1rem !important; }
            .text-2xl { font-size: 1.3rem; line-height: 1.4; }
            strong { font-family: ${isRTL ? "'Amiri', serif" : "'Press Start 2P', cursive"}; font-size: 0.85em; background: linear-gradient(90deg, #ff00cc, #00ccff); -webkit-background-clip: text; -webkit-text-fill-color: transparent; text-shadow: none; display: inline-block; padding: 5px 0; }
            .text-gray-500 { color: #ff00cc; }
            .text-gray-600 { color: #0000cc; }
            .text-gray-800 { color: #0066ff; }
            .border-gray-200 { border-color: #00ccff; height: 4px; background: repeating-linear-gradient(to right, #ff00cc 0px, #ff00cc 10px, #00ccff 10px, #00ccff 20px); }
            .rounded-xl, .rounded-2xl { border-radius: 0; }
            .image-container { position: relative; margin: 30px 0; border: 8px solid transparent; border-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='75' height='75'%3E%3Cg fill='none' stroke-width='2'%3E%3Cpath stroke='%2300ccff' d='M0 0h75v75H0z'/%3E%3Cpath stroke='%23ff00cc' d='M15 15h45v45H15z'/%3E%3C/g%3E%3Cpath fill='%2300ccff' d='M0 0h15v15H0V0zm60 0h15v15H60V0zM0 60h15v15H0V60zm60 0h15v15H60V60z'/%3E%3C/svg%3E") 25; box-shadow: 6px 6px 0 #0066ff, -6px -6px 0 #ff00cc; }
            .image-container::before { content: ''; position: absolute; top: 0; left: 0; right: 0; height: 8px; background: repeating-linear-gradient(to right, #ff00cc 0px, #ff00cc 10px, #00ccff 10px, #00ccff 20px); }
            .image-container::after { content: ''; position: absolute; bottom: 0; left: 0; right: 0; height: 8px; background: repeating-linear-gradient(to right, #00ccff 0px, #00ccff 10px, #ff00cc 10px, #ff00cc 20px); }
            .image-container img { width: 100%; display: block; image-rendering: pixelated; border: 2px dashed #0066ff; }
            a { color: #00ccff; text-decoration: none; font-weight: bold; text-shadow: 1px 1px #ff00cc; transition: all 0.3s; }
            a:hover { color: #ff00cc; text-shadow: 1px 1px #00ccff; text-decoration: underline; }
            @media (max-width: 768px) { 
                body { padding: 10px; } 
                .text-4xl { font-size: 1.4rem; } 
                .text-2xl { font-size: 1rem; } 
                strong { font-size: 0.75em; }
                .marquee { font-size: 8px; }
                .max-w-2xl { border-width: 4px; box-shadow: 4px 4px 0 #0ff, -4px -4px 0 #f0f; }
                .max-w-2xl::before { top: -8px; left: -8px; right: -8px; height: 20px; }
                .image-container { border-width: 5px; margin: 20px 0; }
                .gif { width: 40px; height: 40px; }
                .gif-1 { ${isRTL ? "right" : "left"}: -5px; }
                .gif-2 { ${isRTL ? "left" : "right"}: -5px; }
                .retro-decorations { height: 60px; }
            }
            @media print {
                body { background: white; }
                .max-w-2xl { box-shadow: none; border: 1px solid #ccc; }
                .max-w-2xl::before { display: none; }
                .retro-decorations { display: none; }
                .image-container { box-shadow: none; border: 1px solid #ccc; }
                .image-container::before, .image-container::after { display: none; }
                .image-container img { border: none; }
                h1, h2 { color: black; text-shadow: none; }
                strong { background: none; -webkit-text-fill-color: initial; color: black; }
                .footer { color: black; animation: none; }
                .border-gray-200 { border-top: 1px solid black; height: auto; background: none; }
            }
        `,
        templates: {
            bodyWrapper: (content) =>
                `<div class="max-w-2xl w-full bg-white rounded-2xl shadow-lg p-6">${content}</div>`,
            header: (text, isRTL) =>
                `<div class="mb-6 ${isRTL ? "text-left" : "text-right"} text-gray-500 text-sm">${text} <a href="https://github.com/Hassan-ach" class="underline hover:text-gray-700">Bagi</a></div>`,
            title: (title) =>
                `<h1 class="text-4xl text-gray-800 mb-4">${title}</h1>`,
            image: (url) =>
                `<div class="image-container"><img src="${url}" alt="Video thumbnail" /></div>`,
            sectionContainer: (title, list) => `<div>${title}${list}</div>`,
            sectionTitle: (title) =>
                `<h2 class="text-2xl text-gray-800 mb-4">${title}</h2>`,
            bulletList: (items) => `<ul class="text-gray-600">${items}</ul>`,
            bulletItem: (bold, text) =>
                `<li><strong>${bold}</strong><br /><div class="bullet-content">${text}</div></li>`,
            footer: () =>
                `<div class="footer"><hr class="my-6 border-gray-200" /><p>Made with ❤️ by Bagi</p></div>`,
        },
    },
    hacker: {
        pageTitle: (title) => `Glim: ${title}`,
        useTailwind: true,
        fonts: `<link href="https://fonts.googleapis.com/css2?family=Fira+Code:wght@400;700&display=swap" rel="stylesheet" />`,
        bodyClass: "min-h-screen flex items-center justify-center p-4",
        styles: (isRTL) => `
            @keyframes flicker { 0%, 100% { opacity: 0.9; } 50% { opacity: 1; } }
            @keyframes scanlines { 0% { transform: translateY(0); } 100% { transform: translateY(100vh); } }
            @keyframes typing { 0% { width: 0; } 100% { width: 100%; } }
            @keyframes blink { 0%, 100% { opacity: 1; } 50% { opacity: 0; } }
            @keyframes glitch { 
                0% { text-shadow: 0.05em 0 0 #00ff00, -0.05em -0.025em 0 #0000ff; }
                14% { text-shadow: 0.05em 0 0 #00ff00, -0.05em -0.025em 0 #0000ff; }
                15% { text-shadow: -0.05em -0.025em 0 #00ff00, 0.025em 0.025em 0 #0000ff; }
                49% { text-shadow: -0.05em -0.025em 0 #00ff00, 0.025em 0.025em 0 #0000ff; }
                50% { text-shadow: 0.025em 0.05em 0 #00ff00, 0.05em 0 0 #0000ff; }
                99% { text-shadow: 0.025em 0.05em 0 #00ff00, 0.05em 0 0 #0000ff; }
                100% { text-shadow: -0.025em 0 0 #00ff00, -0.025em -0.025em 0 #0000ff; }
            }
            @keyframes terminal-loading { 
                0% { content: '[■□□□□□□□□□] 10%'; }
                10% { content: '[■■□□□□□□□□] 20%'; }
                20% { content: '[■■■□□□□□□□] 30%'; }
                30% { content: '[■■■■□□□□□□] 40%'; }
                40% { content: '[■■■■■□□□□□] 50%'; }
                50% { content: '[■■■■■■□□□□] 60%'; }
                60% { content: '[■■■■■■■□□□] 70%'; }
                70% { content: '[■■■■■■■■□□] 80%'; }
                80% { content: '[■■■■■■■■■□] 90%'; }
                90%, 100% { content: '[■■■■■■■■■■] 100%'; }
            }
            body { background-color: #000; color: #00ff00; font-family: 'Fira Code', monospace; direction: ${isRTL ? "rtl" : "ltr"}; text-align: ${isRTL ? "right" : "left"}; position: relative; animation: flicker 3s infinite; }
            body::before { content: ''; position: fixed; top: 0; left: 0; width: 100%; height: 2px; background: linear-gradient(90deg, transparent, #00ff00, transparent); animation: scanlines 2s linear infinite; z-index: 1000; opacity: 0.3; }
            body::after { content: ''; position: fixed; top: 0; left: 0; width: 100%; height: 100%; background: repeating-linear-gradient(0deg, rgba(0, 255, 0, 0.03), rgba(0, 255, 0, 0.03) 1px, transparent 1px, transparent 2px); pointer-events: none; z-index: 999; }
            .max-w-2xl { background-color: rgba(0, 20, 0, 0.8); border: 2px solid #00ff00; border-radius: 8px; box-shadow: 0 0 20px #00ff00; position: relative; overflow: hidden; }
            .max-w-2xl::before { content: 'glim@github:~$'; position: absolute; top: 0; left: 0; padding: 8px 10px; background: #003300; color: #00ff00; font-size: 14px; border-bottom: 2px solid #00ff00; width: 100%; box-sizing: border-box; }
            h1, h2 { font-weight: 700; margin-bottom: 0.5rem; color: #00ff00; text-shadow: 0 0 10px #00ff00; padding-top: 10px; }
            h1 { animation: glitch 1s linear infinite; margin-top: 20px; }
            ul { list-style-type: disc; ${isRTL ? "margin-right: 1.5rem;" : "margin-left: 1.5rem;"} margin-bottom: 1.5rem; }
            li { margin-bottom: 1rem; color: #00ff00; position: relative; }
            li::before { content: '> '; position: absolute; left: -20px; color: #00ff00; }
            li strong { color: #ffffff; text-shadow: 0 0 5px #ffffff; position: relative; }
            li strong::after { content: '_'; animation: blink 1s infinite; }
            ol { list-style-type: decimal; ${isRTL ? "margin-right: 2rem;" : "margin-left: 2rem;"}; margin-top: 0.5rem; }
            ol li { margin-bottom: 0.2rem; }
            ol li::before { content: ''; }
            .bullet-content ol { margin-top: 0.3rem; margin-bottom: 0.3rem; }
            .footer { text-align: center; margin-top: 2rem; font-size: 0.9rem; color: #ffffff; }
            a { color: #00ff00; text-decoration: underline; position: relative; }
            a:hover { color: #ffffff; text-shadow: 0 0 10px #ffffff; }
            a:focus { outline: 1px solid #00ff00; outline-offset: 2px; }
            .text-gray-500 { color: #00ff00; }
            .text-gray-600 { color: #00ff00; }
            .text-gray-800 { color: #00ff00; }
            .border-gray-200 { border-color: #00ff00; }
            .bg-white { background-color: transparent; }
            .image-container { position: relative; margin-bottom: 1.5rem; border: 2px solid #00ff00; border-radius: 8px; overflow: hidden; box-shadow: 0 0 15px rgba(0, 255, 0, 0.3); }
            .image-container::before { content: '[LOADING IMAGE...]'; position: absolute; top: 0; left: 0; width: 100%; height: 100%; display: flex; justify-content: center; align-items: center; flex-direction: column; background-color: rgba(0, 20, 0, 0.7); color: #00ff00; font-family: 'Fira Code', monospace; z-index: 2; animation: typing 1s steps(14) forwards, flicker 2s infinite; overflow: hidden; white-space: nowrap; }
            .image-container::after { content: ''; position: absolute; top: 60%; width: 100%; text-align: center; animation: terminal-loading 2s steps(10) forwards; color: #00ff00; font-family: 'Fira Code', monospace; }
            .image-container img { width: 100%; display: block; filter: sepia(10%) hue-rotate(80deg) brightness(0.8) contrast(1.2); }
            @media (max-width: 768px) { body { padding: 10px; } }
            @media print { 
                body { background-color: white; color: black; }
                body::before, body::after { display: none; }
                .max-w-2xl { background: white; border: 1px solid black; box-shadow: none; }
                .max-w-2xl::before { display: none; }
                h1, h2, li, .text-gray-500, .text-gray-600, .text-gray-800 { color: black; text-shadow: none; animation: none; }
                li strong { color: black; text-shadow: none; }
                li strong::after { display: none; }
                .image-container { border: 1px solid black; box-shadow: none; }
                .image-container::before, .image-container::after { display: none; }
                .image-container img { filter: none; }
            }
        `,
        templates: {
            bodyWrapper: (content) =>
                `<div class="max-w-2xl w-full bg-white rounded-2xl shadow-lg p-6">${content}</div>`,
            header: (text, isRTL) =>
                `<div class="mb-6 ${isRTL ? "text-left" : "text-right"} text-gray-500 text-sm">${text} <a href="https://github.com/Hassan-ach" class="underline hover:text-gray-700">Bagi</a></div>`,
            title: (title) =>
                `<h1 class="text-4xl text-gray-800 mb-4">${title}</h1>`,
            image: (url) =>
                `<div class="image-container"><img src="${url}" alt="Video thumbnail" /></div>`,
            sectionContainer: (title, list) => `<div>${title}${list}</div>`,
            sectionTitle: (title) =>
                `<h2 class="text-2xl text-gray-800 mb-4">${title}</h2>`,
            bulletList: (items) => `<ul class="text-gray-600">${items}</ul>`,
            bulletItem: (bold, text) =>
                `<li><strong>${bold}</strong><br /><div class="bullet-content">${text}</div></li>`,
            footer: () =>
                `<div class="footer"><hr class="my-6 border-gray-200" /><p>Made with ❤️ by Bagi</p></div>`,
        },
    },
    typography: {
        pageTitle: (title) => `Glim: ${title}`,
        useTailwind: true,
        fonts: `<link href="https://fonts.googleapis.com/css2?family=Oswald:wght@700&family=Space+Grotesk:wght@400;700&family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet" />`,
        bodyClass: "min-h-screen flex items-center justify-center p-4",
        styles: (isRTL) => `
            :root { --primary-black: #121212; --accent-gray: #333333; --medium-gray: #666666; --light-gray: #eeeeee; --primary-white: #ffffff; }
            body { background-color: var(--primary-white); font-family: ${isRTL ? "'Amiri', serif" : "'Inter', sans-serif"}; direction: ${isRTL ? "rtl" : "ltr"}; text-align: ${isRTL ? "right" : "left"}; line-height: 1.6; color: var(--primary-black); }
            h1 { font-family: ${isRTL ? "'Amiri', serif" : "'Oswald', sans-serif"}; font-weight: 700; line-height: 1.1; letter-spacing: ${isRTL ? "0" : "-1px"}; }
            h2 { font-family: ${isRTL ? "'Amiri', serif" : "'Space Grotesk', sans-serif"}; font-weight: 700; line-height: 1.2; letter-spacing: ${isRTL ? "0" : "-0.5px"}; }
            .max-w-2xl { max-width: 720px; }
            ul { list-style-type: disc; ${isRTL ? "margin-right: 1.5rem;" : "margin-left: 1.5rem;"} margin-bottom: 1.5rem; }
            li { margin-bottom: 1.2rem; position: relative; }
            li::marker { color: var(--accent-gray); }
            li strong { display: block; font-family: ${isRTL ? "'Amiri', serif" : "'Space Grotesk', sans-serif"}; font-weight: 700; margin-bottom: 0.5rem; font-size: 1.1em; }
            ol { list-style-type: decimal; ${isRTL ? "margin-right: 2rem;" : "margin-left: 2rem;"}; margin-top: 0.5rem; }
            ol li { margin-bottom: 0.3rem; }
            .bullet-content ol { margin-top: 0.3rem; margin-bottom: 0.3rem; }
            .footer { text-align: center; margin-top: 2rem; font-size: 0.9rem; color: var(--medium-gray); }
            .text-4xl { font-size: 3rem; }
            .text-2xl { font-size: 2rem; }
            .image-container { margin-bottom: 2rem; position: relative; }
            .image-container::before { content: ''; position: absolute; top: 0; left: 0; width: 100%; height: 100%; background: linear-gradient(135deg, rgba(0,0,0,0.05) 0%, rgba(0,0,0,0) 100%); z-index: 1; border-radius: 0.75rem; }
            .image-container img { width: 100%; border-radius: 0.75rem; display: block; box-shadow: 0 10px 30px rgba(0,0,0,0.1); }
            .image-container:after { content: ''; width: 100%; height: 1px; background: linear-gradient(to right, transparent, var(--medium-gray), transparent); display: block; margin-top: 1.5rem; }
            /* Enhanced typography styling */
            .max-w-2xl p { margin-bottom: 1.2em; }
            a { color: #4361ee; text-decoration: none; border-bottom: 1px solid rgba(67, 97, 238, 0.3); transition: border-color 0.2s ease, color 0.2s ease; }
            a:hover { color: #2d46d1; border-color: #2d46d1; }
            a:focus { outline: 2px solid #4361ee; outline-offset: 2px; }
            h2:not(:first-of-type) { margin-top: 3rem; }
            @media (max-width: 768px) { body { padding: 1rem; } .text-4xl { font-size: 2.5rem; } .text-2xl { font-size: 1.5rem; } }
            @media print {
                body { color: black; background: white; }
                .image-container { box-shadow: none; page-break-inside: avoid; }
                .image-container img { box-shadow: none; }
                h2 { page-break-after: avoid; }
                li { page-break-inside: avoid; }
                .max-w-2xl { width: 100%; max-width: 100%; margin: 0; padding: 0; }
            }
        `,
        templates: {
            bodyWrapper: (content) =>
                `<div class="max-w-2xl w-full bg-white rounded-2xl shadow-lg p-6">${content}</div>`,
            header: (text, isRTL) =>
                `<div class="mb-6 ${isRTL ? "text-left" : "text-right"} text-gray-500 text-sm">${text} <a href="https://github.com/Hassan-ach" class="underline hover:text-gray-700">Bagi</a></div>`,
            title: (title) =>
                `<h1 class="text-4xl text-gray-800 mb-4">${title}</h1>`,
            image: (url) =>
                `<div class="image-container"><img src="${url}" alt="Video thumbnail" /></div>`,
            sectionContainer: (title, list) => `<div>${title}${list}</div>`,
            sectionTitle: (title) =>
                `<h2 class="text-2xl text-gray-800 mb-4">${title}</h2>`,
            bulletList: (items) => `<ul class="text-gray-600">${items}</ul>`,
            bulletItem: (bold, text) =>
                `<li><strong>${bold}</strong><br /><div class="bullet-content">${text}</div></li>`,
            footer: () =>
                `<div class="footer"><hr class="my-6 border-gray-200" /><p>Made with ❤️ by Bagi</p></div>`,
        },
    },
    maximalist: {
        pageTitle: (title) => `Glim - Maximalist Edition: ${title}`,
        useTailwind: true,
        fonts: `<link href="https://fonts.googleapis.com/css2?family=Bungee&family=Righteous&family=Caveat:wght@400;700&display=swap" rel="stylesheet" />`,
        bodyClass: "min-h-screen flex items-center justify-center p-4",
        extraContent: `
            <div class="floating-element floating-1">★</div> <div class="floating-element floating-2">◆</div> <div class="floating-element floating-3">●</div>
            <div class="floating-element floating-4">▲</div> <div class="floating-element floating-5">♦</div> <div class="floating-element floating-6">◉</div>
        `,
        styles: (isRTL) => `
            @keyframes float { 0%, 100% { transform: translateY(0px) rotate(0deg); } 50% { transform: translateY(-20px) rotate(5deg); } }
            @keyframes bg-shift { 0% { background-position: 0% 50% } 50% { background-position: 100% 50% } 100% { background-position: 0% 50% } }
            @keyframes pulse-rainbow { 0% { box-shadow: 0 0 30px rgba(255,0,110,0.5); } 25% { box-shadow: 0 0 30px rgba(131,56,236,0.5); } 50% { box-shadow: 0 0 30px rgba(58,134,255,0.5); } 75% { box-shadow: 0 0 30px rgba(6,255,165,0.5); } 100% { box-shadow: 0 0 30px rgba(255,190,11,0.5); } }
            @keyframes shine { 0% { background-position: -200% 50%; } 100% { background-position: 200% 50%; } }
            body { background-color: #000; font-family: ${isRTL ? "'Amiri', serif" : "'Caveat', cursive"}; direction: ${isRTL ? "rtl" : "ltr"}; text-align: ${isRTL ? "right" : "left"}; margin: 0; padding: 20px; min-height: 100vh; position: relative; overflow-x: hidden; }
            body::before { content: ''; position: fixed; top: 0; left: 0; width: 100%; height: 100%; background-image: radial-gradient(circle at 25% 25%, #ff006e 2px, transparent 2px), radial-gradient(circle at 75% 75%, #8338ec 3px, transparent 3px), radial-gradient(circle at 50% 10%, #06ffa5 1px, transparent 1px), radial-gradient(circle at 10% 90%, #ffbe0b 2px, transparent 2px); background-size: 50px 50px, 80px 80px, 30px 30px, 60px 60px; opacity: 0.4; z-index: -1; animation: float 6s ease-in-out infinite; }
            .floating-element { position: absolute; animation: float 4s ease-in-out infinite; font-size: 2rem; z-index: 5; }
            .floating-1 { top: 10%; left: 5%; color: #ff006e; animation-delay: 0s; } .floating-2 { top: 20%; right: 10%; color: #8338ec; animation-delay: 1s; } .floating-3 { bottom: 30%; left: 8%; color: #3a86ff; animation-delay: 2s; } .floating-4 { bottom: 10%; right: 15%; color: #06ffa5; animation-delay: 3s; } .floating-5 { top: 50%; left: 2%; color: #ffbe0b; animation-delay: 0.5s; } .floating-6 { top: 70%; right: 5%; color: #fb8500; animation-delay: 1.5s; }
            .max-w-2xl { position: relative; z-index: 10; background: linear-gradient(135deg, rgba(255,255,255,0.9) 0%, rgba(255,255,255,0.7) 50%, rgba(255,255,255,0.9) 100%); backdrop-filter: blur(10px); border: 5px solid; border-image: linear-gradient(45deg, #ff006e, #8338ec, #3a86ff, #06ffa5, #ffbe0b) 1; box-shadow: 0 0 50px rgba(255,0,110,0.5), inset 0 0 50px rgba(255,255,255,0.1), 0 20px 40px rgba(0,0,0,0.3); animation: pulse-rainbow 4s ease-in-out infinite; }
            h1, h2 { font-weight: 700; margin-bottom: 0.5rem; }
            h1 { font-family: 'Bungee', cursive; background: linear-gradient(45deg, #ff006e, #8338ec, #3a86ff, #06ffa5, #ffbe0b); background-size: 400% 400%; -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text; animation: bg-shift 3s ease infinite; text-shadow: 2px 2px 4px rgba(0,0,0,0.3); transform: rotate(-2deg); position: relative; z-index: 15; }
            h2 { font-family: 'Righteous', cursive; background: linear-gradient(90deg, #e73c7e, #23a6d5); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text; position: relative; z-index: 12; }
            h2::before { content: '★'; position: absolute; left: ${isRTL ? "auto" : "-30px"}; right: ${isRTL ? "-30px" : "auto"}; color: #ffbe0b; font-size: 1.5em; animation: float 2s ease-in-out infinite; }
            .image-container { position: relative; overflow: hidden; border-radius: 20px; margin-bottom: 1.5rem; z-index: 11; background: linear-gradient(45deg, #ff006e, #8338ec, #3a86ff, #06ffa5, #ffbe0b); padding: 4px; animation: bg-shift 5s ease infinite; }
            .image-container::before { content: ''; position: absolute; top: -50%; left: -50%; width: 200%; height: 200%; background: linear-gradient(90deg, transparent, rgba(255,255,255,0.6), transparent); background-size: 200% 100%; transform: rotate(45deg); animation: shine 3s linear infinite; z-index: 2; pointer-events: none; }
            .image-container::after { content: ''; position: absolute; inset: 0; background: radial-gradient(circle at 50% 100%, rgba(255,255,255,0.2), transparent 50%); z-index: 1; }
            .image-container img { border-radius: 18px; width: 100%; display: block; position: relative; z-index: 0; }
            /* Animated corner accents */
            .image-container .corner { position: absolute; width: 15px; height: 15px; z-index: 3; }
            .image-container .corner-tl { top: 5px; left: 5px; border-top: 3px solid #ff006e; border-left: 3px solid #ff006e; }
            .image-container .corner-tr { top: 5px; right: 5px; border-top: 3px solid #3a86ff; border-right: 3px solid #3a86ff; }
            .image-container .corner-bl { bottom: 5px; left: 5px; border-bottom: 3px solid #06ffa5; border-left: 3px solid #06ffa5; }
            .image-container .corner-br { bottom: 5px; right: 5px; border-bottom: 3px solid #ffbe0b; border-right: 3px solid #ffbe0b; }
            ul { list-style-type: disc; ${isRTL ? "margin-right: 1.5rem;" : "margin-left: 1.5rem;"} margin-bottom: 1.5rem; list-style: none; position: relative; z-index: 10; padding: 0; }
            li { margin-bottom: 1rem; background: linear-gradient(90deg, rgba(255,0,110,0.1), rgba(58,134,255,0.1), rgba(6,255,165,0.1)); border-${isRTL ? "right" : "left"}: 5px solid #ff006e; padding: 15px; border-radius: 10px; box-shadow: 0 5px 15px rgba(0,0,0,0.1); position: relative; font-family: 'Caveat', cursive; font-size: 1.2em; }
            li strong { font-family: 'Righteous', cursive; color: #8338ec; display: block; margin-bottom: 10px; font-size: 1.3em; text-shadow: 2px 2px 3px rgba(131,56,236,0.3); }
            ol { list-style-type: decimal; ${isRTL ? "margin-right: 2rem;" : "margin-left: 2rem;"}; margin-top: 0.5rem; }
            ol li { margin-bottom: 0.2rem; border-left: none; background: none; box-shadow: none; padding: 0; }
            .bullet-content ol { margin-top: 0.3rem; margin-bottom: 0.3rem; }
            .bullet-content { color: #333; line-height: 1.4; }
            .footer { text-align: center; padding: 20px 0; font-family: 'Righteous', cursive; background: linear-gradient(90deg, #ff006e, #8338ec, #3a86ff); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text; font-size: 1.2em; position: relative; z-index: 10; margin-top: 2rem; }
            .footer hr { height: 3px; border: none; background: linear-gradient(90deg, #ff006e, #8338ec, #3a86ff, #06ffa5, #ffbe0b); margin-bottom: 15px; }
            .mb-6 { margin-bottom: 1.5rem; }
            .text-gray-500 { font-family: 'Righteous', cursive; background: linear-gradient(45deg, #ff006e, #8338ec); color: white !important; padding: 10px 15px; border-radius: 25px; font-size: 0.9em; box-shadow: 0 5px 15px rgba(255,0,110,0.4); z-index: 20; transform: rotate(5deg); }
            .text-gray-500 a { color: #06ffa5 !important; text-decoration: none; font-weight: bold; }
            .text-gray-500 a:hover { color: #ffbe0b !important; text-shadow: 0 0 10px rgba(255,190,11,0.8); }
            .text-gray-600 { color: #333 !important; }
            .text-gray-800 { color: transparent !important; }
            .text-4xl { font-size: 2.5rem; }
            .text-2xl { font-size: 1.8rem; }
            .rounded-xl, .rounded-2xl { border-radius: 20px; }
            @media (max-width: 768px) { .floating-element { display: none; } .title { font-size: 2rem; } h2 { font-size: 1.5rem; } .text-gray-500 { position: static; transform: none; margin-bottom: 20px; text-align: center; } }
        `,
        templates: {
            bodyWrapper: (content) =>
                `<div class="max-w-2xl w-full bg-white rounded-2xl shadow-lg p-6">${content}</div>`,
            header: (text, isRTL) =>
                `<div class="mb-6 ${isRTL ? "text-left" : "text-right"} text-gray-500 text-sm">${text} <a href="https://github.com/Hassan-ach" class="underline hover:text-gray-700">Bagi</a></div>`,
            title: (title) =>
                `<h1 class="text-4xl text-gray-800 mb-4">${title}</h1>`,
            image: (url) =>
                `<div class="image-container"><div class="corner corner-tl"></div><div class="corner corner-tr"></div><div class="corner corner-bl"></div><div class="corner corner-br"></div><img src="${url}" alt="Video thumbnail" class="w-full" /></div>`,
            sectionContainer: (title, list) => `<div>${title}${list}</div>`,
            sectionTitle: (title) =>
                `<h2 class="text-2xl text-gray-800 mb-4">${title}</h2>`,
            bulletList: (items) => `<ul class="text-gray-600">${items}</ul>`,
            bulletItem: (bold, text) =>
                `<li><strong>${bold}</strong><br /><div class="bullet-content">${text}</div></li>`,
            footer: () =>
                `<div class="footer"><hr class="my-6 border-gray-200" /><p>Made with ❤️ by Bagi</p></div>`,
        },
    },
    brutalist: {
        pageTitle: (title) => `BRUTALIST: ${title}`,
        useTailwind: false,
        fonts: `<link href="https://fonts.googleapis.com/css2?family=Courier+Prime:wght@400;700&family=Inter:wght@900&display=swap" rel="stylesheet" />`,
        bodyClass: "min-h-screen flex items-center justify-center p-4",
        styles: (isRTL) => `
            /* Brutalist design principles: raw materials, unrefined typography, visible construction */
            body { 
                background-color: #ffffff; 
                font-family: ${isRTL ? "'Amiri', serif" : "'Courier Prime', 'Courier New', monospace"}; 
                direction: ${isRTL ? "rtl" : "ltr"}; 
                text-align: ${isRTL ? "right" : "left"}; 
                color: #000000; 
                margin: 0; 
                padding: 20px; 
                line-height: 1.4;
                background-image: url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%23000000' fill-opacity='0.05'%3E%3Cpath d='M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E");
            }
            .max-w-2xl { 
                max-width: 800px; 
                width: 100%; 
                background-color: #f5f5f5; 
                border: 5px solid #000000; 
                padding: 25px; 
                margin: 0 auto;
                position: relative;
                box-shadow: 12px 12px 0px #000000; 
            }
            .max-w-2xl::before {
                content: '';
                position: absolute;
                top: -15px;
                left: -15px;
                width: 30px;
                height: 30px;
                background-color: #000000;
                z-index: -1;
            }
            .max-w-2xl::after {
                content: '';
                position: absolute;
                bottom: -15px;
                right: -15px;
                width: 30px;
                height: 30px;
                background-color: #000000;
                z-index: -1;
            }
            h1, h2 { 
                font-weight: 900; 
                margin-bottom: 1rem; 
                font-family: ${isRTL ? "'Amiri', serif" : "'Inter', sans-serif"}; 
                text-transform: uppercase;
                letter-spacing: -1px;
            }
            h1 { 
                font-weight: 900; 
                margin: 0 0 30px 0; 
                font-size: 28px; 
                border: 5px solid #000000; 
                padding: 15px; 
                background-color: #000000; 
                color: #ffffff;
                position: relative;
                left: -35px;
                width: calc(100% + 70px);
                box-shadow: 8px 8px 0 #f5f5f5, 10px 10px 0 #000000;
            }
            h2 { 
                font-weight: 900; 
                margin: 40px 0 20px 0; 
                font-size: 20px; 
                border: 5px solid #000000; 
                padding: 10px; 
                background-color: #ffffff; 
                color: #000000;
                position: relative;
                ${isRTL ? 
                    "right: -15px; padding-right: 25px;" : 
                    "left: -15px; padding-left: 25px;"}
                width: calc(100% + 30px);
            }
            h2::before {
                content: "//";
                position: absolute;
                ${isRTL ? "left: 10px;" : "right: 10px;"}
                top: 10px;
                font-family: ${isRTL ? "'Amiri', serif" : "'Courier Prime', monospace"};
            }
            .mb-6 { 
                margin-bottom: 1.5rem; 
                border: 5px solid #000000; 
                padding: 10px; 
                background-color: #ffffff; 
                ${isRTL ? "text-align: left;" : "text-align: right;"} 
                font-size: 12px;
                text-transform: uppercase;
                font-weight: bold;
            }
            ul { 
                list-style-type: none; 
                margin: 0; 
                padding: 0; 
                border: 5px solid #000000; 
                background-color: #ffffff; 
                ${isRTL ? "margin-right: 0;" : "margin-left: 0;"}
            }
            li { 
                margin: 0; 
                padding: 20px; 
                border-bottom: 5px solid #000000;
                position: relative;
            }
            li:last-child { border-bottom: none; }
            li::before {
                content: "■";
                position: absolute;
                ${isRTL ? "right: 5px;" : "left: 5px;"}
                top: 20px;
                font-size: 10px;
            }
            li strong { 
                display: block; 
                margin-bottom: 10px; 
                font-size: 16px; 
                text-transform: uppercase;
                font-weight: 900;
                letter-spacing: 1px;
                padding: 5px 0;
                border-bottom: 3px dashed #000000;
            }
            .bullet-content { 
                font-size: 14px;
                padding: ${isRTL ? "0 15px 0 0" : "0 0 0 15px"};
            }
            ol { 
                list-style-type: decimal; 
                ${isRTL ? "margin-right: 25px;" : "margin-left: 25px;"} 
                margin: 10px 0;
                border: 3px solid #000000;
                padding: 10px ${isRTL ? "25px 10px 10px" : "10px 10px 25px"};
                background-color: #f5f5f5;
            }
            ol li { 
                border: none; 
                border-bottom: 1px solid #000000;
                padding: 5px 0; 
                margin: 0;
            }
            ol li::before { content: none; }
            ol li:last-child { border-bottom: none; }
            .footer { 
                border: 5px solid #000000; 
                padding: 15px; 
                margin-top: 40px; 
                background-color: #ffffff; 
                text-align: center; 
                font-size: 14px; 
                text-transform: uppercase;
                font-weight: bold;
                position: relative;
            }
            .footer::before {
                content: "///////////////////";
                position: absolute;
                top: -15px;
                left: 50%;
                transform: translateX(-50%);
                background: #f5f5f5;
                padding: 0 10px;
            }
            .text-gray-500 { font-size: 14px; font-weight: bold; }
            .text-gray-500 a { 
                color: #000000; 
                font-weight: bold; 
                text-decoration: none;
                background-color: yellow;
                padding: 0 5px;
                border: 2px solid #000000;
            }
            .text-gray-500 a:hover { text-decoration: underline; background-color: #000000; color: yellow; }
            .text-gray-500 a:focus { outline: 3px solid #000000; }
            .text-gray-600 { color: #000000; }
            .text-gray-800 { color: #000000; }
            .rounded-xl, .rounded-2xl { border-radius: 0; }
            .image-container { 
                border: 5px solid #000000; 
                margin: 30px 0; 
                background-color: #ffffff;
                position: relative;
                padding: 5px;
            }
            .image-container::before { 
                content: 'IMAGE'; 
                display: block; 
                text-align: center; 
                padding: 5px; 
                background-color: #000000; 
                color: #ffffff; 
                font-weight: bold; 
                font-family: ${isRTL ? "'Amiri', serif" : "'Courier Prime', monospace"};
                letter-spacing: 2px;
            }
            .image-container::after {
                content: '';
                position: absolute;
                top: 5px;
                right: 5px;
                border-left: 15px solid transparent;
                border-bottom: 15px solid transparent;
                border-right: 15px solid #000000;
                border-top: 15px solid #000000;
            }
            .image-container img { 
                width: 100%; 
                height: auto; 
                display: block;
                border: 3px solid #000000;
                filter: grayscale(20%);
            }
            .border-gray-200 { border-color: #000000; height: 5px; background: #000000; }
            .my-6 { margin-top: 1.5rem; margin-bottom: 1.5rem; }
            
            /* Responsive adjustments */
            @media (max-width: 768px) { 
                body { padding: 15px 10px; } 
                .max-w-2xl { 
                    padding: 15px; 
                    box-shadow: 8px 8px 0px #000000;
                    border-width: 4px;
                } 
                h1 { 
                    font-size: 20px; 
                    left: -25px;
                    width: calc(100% + 50px);
                    border-width: 4px;
                } 
                h2 { 
                    font-size: 16px;
                    ${isRTL ? "right: -10px;" : "left: -10px;"}
                    width: calc(100% + 20px);
                    border-width: 4px;
                }
                .image-container, ul, .footer, .mb-6 { border-width: 4px; }
                .footer::before { top: -12px; }
                ol { border-width: 2px; }
            }
            
            /* Print styles */
            @media print {
                body { background: white; background-image: none; }
                .max-w-2xl { 
                    box-shadow: none; 
                    border: 2px solid black;
                    padding: 10px;
                }
                .max-w-2xl::before, .max-w-2xl::after { display: none; }
                h1 { 
                    position: static;
                    width: auto;
                    box-shadow: none;
                    border-width: 2px;
                    margin: 0 0 20px 0;
                }
                h2 { 
                    position: static;
                    width: auto;
                    border-width: 2px;
                }
                .image-container, ul, .footer, .mb-6 { border-width: 2px; }
                .image-container::after { display: none; }
                li::before { color: black; }
            }
        `,
        templates: {
            bodyWrapper: (content) =>
                `<div class="max-w-2xl w-full bg-white rounded-2xl shadow-lg p-6">${content}</div>`,
            header: (text, isRTL) =>
                `<div class="mb-6 ${isRTL ? "text-left" : "text-right"} text-gray-500 text-sm">${text} <a href="https://github.com/Hassan-ach" class="underline hover:text-gray-700">Bagi</a></div>`,
            title: (title) =>
                `<h1 class="text-4xl text-gray-800 mb-4">${title}</h1>`,
            image: (url) =>
                `<div class="image-container"><img src="${url}" alt="Video thumbnail" /></div>`,
            sectionContainer: (title, list) => `<div>${title}${list}</div>`,
            sectionTitle: (title) =>
                `<h2 class="text-2xl text-gray-800 mb-4">${title}</h2>`,
            bulletList: (items) => `<ul class="text-gray-600">${items}</ul>`,
            bulletItem: (bold, text) =>
                `<li><strong>${bold}</strong><br /><div class="bullet-content">${text}</div></li>`,
            footer: () =>
                `<div class="footer"><hr class="my-6 border-gray-200" /><p>Made with ❤️ by Bagi</p></div>`,
        },
    },
    flat: {
        pageTitle: (title) => `Glim: ${title}`,
        useTailwind: false,
        fonts: `<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap" rel="stylesheet" />`,
        bodyClass: "min-h-screen flex items-center justify-center p-4",
        styles: (isRTL) => `
            body { background-color: #2563eb; font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif; direction: ${isRTL ? "rtl" : "ltr"}; text-align: ${isRTL ? "right" : "left"}; margin: 0; padding: 20px; min-height: 100vh; display: flex; align-items: center; justify-content: center; }
            .max-w-2xl { max-width: 800px; width: 100%; background-color: #ffffff; border-radius: 0; padding: 40px; margin: 0 auto; }
            h1, h2 { font-weight: 700; margin-bottom: 0.5rem; }
            h1 { font-size: 32px; font-weight: 700; margin-bottom: 20px; color: #1f2937; line-height: 1.2; }
            h2 { font-size: 24px; font-weight: 600; margin: 30px 0 20px 0; color: #ffffff; background-color: #f59e0b; padding: 12px 20px; margin-left: -40px; margin-right: -40px; }
            .mb-6 { margin-bottom: 1.5rem; margin-top: -40px; margin-left: -40px; margin-right: -40px; background-color: #10b981; color: #ffffff; padding: 20px; ${isRTL ? "text-align: left;" : "text-align: right;"} }
            ul { list-style-type: none; padding: 0; margin-bottom: 30px; ${isRTL ? "margin-right: 0;" : "margin-left: 0;"} }
            li { margin-bottom: 1rem; background-color: #f8fafc; padding: 20px; border-${isRTL ? "right" : "left"}: 6px solid #8b5cf6; }
            li strong { color: #1f2937; font-weight: 700; font-size: 18px; display: block; margin-bottom: 8px; }
            ol { list-style-type: decimal; ${isRTL ? "margin-right: 20px;" : "margin-left: 20px;"} margin-top: 12px; }
            ol li { background: none; border: none; padding: 4px 0; margin-bottom: 6px; color: #4b5563; border-left: none; }
            .bullet-content ol { margin-top: 0.3rem; margin-bottom: 0.3rem; }
            .footer { background-color: #6366f1; color: #ffffff; text-align: center; margin: 40px -40px -40px -40px; padding: 20px; font-size: 16px; font-weight: 600; }
            .footer hr { border: none; height: 2px; background-color: #ffffff; margin: 0 0 15px 0; }
            .text-gray-500 { font-size: 14px; font-weight: 400; }
            .text-gray-500 a { color: #ffffff; text-decoration: underline; font-weight: 600; }
            .text-gray-500 a:hover { color: #f3f4f6; }
            .text-gray-600 { color: #4b5563; }
            .text-gray-800 { color: #1f2937; }
            .rounded-xl, .rounded-2xl { border-radius: 0; }
            .image-container { margin-bottom: 30px; position: relative; background-color: #ffffff; }
            .image-container::before { content: ''; position: absolute; top: 0; left: 0; width: 10px; height: 100%; background-color: #dc2626; z-index: 1; }
            .image-container img { width: 100%; height: auto; display: block; border-top: 4px solid #dc2626; border-bottom: 4px solid #dc2626; }
            .my-6 { margin: 0 0 15px 0; }
            .border-gray-200 { border: none; height: 2px; background-color: #ffffff; }
            .bullet-content { color: #4b5563; font-weight: 400; line-height: 1.6; }
            @media (max-width: 768px) { body { padding: 10px; } .max-w-2xl { padding: 20px; } h1 { font-size: 24px; } h2 { font-size: 20px; margin-left: -20px; margin-right: -20px; } .mb-6 { margin-left: -20px; margin-right: -20px; } .footer { margin: 30px -20px -20px -20px; } }
        `,
        templates: {
            bodyWrapper: (content) =>
                `<div class="max-w-2xl w-full bg-white rounded-2xl shadow-lg p-6">${content}</div>`,
            header: (text, isRTL) =>
                `<div class="mb-6 ${isRTL ? "text-left" : "text-right"} text-gray-500 text-sm">${text} <a href="https://github.com/Hassan-ach" class="underline hover:text-gray-700">Bagi</a></div>`,
            title: (title) =>
                `<h1 class="text-4xl text-gray-800 mb-4">${title}</h1>`,
            image: (url) =>
                `<div class="image-container"><img src="${url}" alt="Video thumbnail" /></div>`,
            sectionContainer: (title, list) => `<div>${title}${list}</div>`,
            sectionTitle: (title) =>
                `<h2 class="text-2xl text-gray-800 mb-4">${title}</h2>`,
            bulletList: (items) => `<ul class="text-gray-600">${items}</ul>`,
            bulletItem: (bold, text) =>
                `<li><strong>${bold}</strong><br /><div class="bullet-content">${text}</div></li>`,
            footer: () =>
                `<div class="footer"><hr class="my-6 border-gray-200" /><p>Made with ❤️ by Bagi</p></div>`,
        },
    },
    minimalist: {
        pageTitle: (title) => `${title} | Glim`,
        useTailwind: false,
        fonts: `<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap" rel="stylesheet" />`,
        bodyClass: "min-h-screen flex items-center justify-center p-4",
        styles: (isRTL) => `
            body { background-color: #ffffff; font-family: 'Inter', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; color: #222222; line-height: 1.7; margin: 0; padding: 3rem 2rem; direction: ${isRTL ? "rtl" : "ltr"}; text-align: ${isRTL ? "right" : "left"}; min-height: 100vh; display: flex; align-items: center; justify-content: center; }
            .max-w-2xl { max-width: 720px; margin: 0 auto; background-color: #ffffff; border-radius: 0; }
            h1, h2 { font-weight: 700; margin-bottom: 0.5rem; }
            h1 { font-size: 2.8rem; margin: 0 0 1rem 0; line-height: 1.2; }
            h2 { font-size: 1.8rem; margin-top: 4rem; margin-bottom: 1.5rem; padding-bottom: 0.5rem; border-bottom: 1px solid #eeeeee; }
            .mb-6 { font-size: 0.9rem; color: #666666; margin-bottom: 2rem; text-align: ${isRTL ? "left" : "right"}; }
            ul { list-style-type: none; padding: 0; margin: 0; ${isRTL ? "margin-right: 0;" : "margin-left: 0;"} }
            li { margin-bottom: 2rem; }
            li strong { display: block; font-size: 1.2rem; margin-bottom: 0.5rem; color: #111111; }
            ol { list-style-type: decimal; ${isRTL ? "margin-right: 2rem;" : "margin-left: 2rem;"} margin-top: 0.5rem; }
            ol li { margin-bottom: 0.3rem; }
            .bullet-content ol { margin-top: 0.3rem; margin-bottom: 0.3rem; }
            .footer { text-align: center; margin-top: 4rem; padding-top: 2rem; font-size: 0.9rem; color: #999999; border-top: 1px solid #eeeeee; }
            .text-gray-500 { color: #666666; }
            .text-gray-500 a { color: #007BFF; text-decoration: none; font-weight: 500; }
            .text-gray-500 a:hover { text-decoration: underline; }
            .text-gray-600 { color: #333333; }
            .text-gray-800 { color: #222222; }
            .rounded-xl, .rounded-2xl { border-radius: 12px; }
            .image-container { margin-bottom: 3rem; }
            .image-container img { width: 100%; display: block; }
            .my-6 { margin-top: 1.5rem; margin-bottom: 1.5rem; }
            .border-gray-200 { border-color: #eeeeee; }
            .bullet-content { color: #333333; font-size: 1rem; }
            @media (max-width: 768px) { body { padding: 1.5rem; } h1 { font-size: 2rem; } h2 { font-size: 1.5rem; } }
        `,
        templates: {
            bodyWrapper: (content) =>
                `<div class="max-w-2xl w-full bg-white rounded-2xl shadow-lg p-6">${content}</div>`,
            header: (text, isRTL) =>
                `<div class="mb-6 ${isRTL ? "text-left" : "text-right"} text-gray-500 text-sm">${text} <a href="https://github.com/Hassan-ach" class="underline hover:text-gray-700">Bagi</a></div>`,
            title: (title) =>
                `<h1 class="text-4xl text-gray-800 mb-4">${title}</h1>`,
            image: (url) =>
                `<div class="image-container"><img src="${url}" alt="Video thumbnail" /></div>`,
            sectionContainer: (title, list) => `<div>${title}${list}</div>`,
            sectionTitle: (title) =>
                `<h2 class="text-2xl text-gray-800 mb-4">${title}</h2>`,
            bulletList: (items) => `<ul class="text-gray-600">${items}</ul>`,
            bulletItem: (bold, text) =>
                `<li><strong>${bold}</strong><br /><div class="bullet-content">${text}</div></li>`,
            footer: () =>
                `<div class="footer"><hr class="my-6 border-gray-200" /><p>Made with ❤️ by Bagi</p></div>`,
        },
    },
    material: {
        pageTitle: (title) => `${title} - Glim`,
        useTailwind: false,
        fonts: `<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&family=Material+Icons&display=swap" rel="stylesheet" />`,
        bodyClass: "min-h-screen flex items-center justify-center p-4",
        styles: (isRTL) => `
            :root { 
                /* Material Design 3 color system */
                --md-primary: #6750A4; 
                --md-primary-dark: #4F378B; 
                --md-primary-light: #D0BCFF;
                --md-secondary: #9C27B0;
                --md-secondary-light: #E8DEF8;
                --md-accent: #E8DEF8;
                --md-tertiary: #7D5260;
                --md-background: #FFFBFE; 
                --md-surface: #FFFFFF; 
                --md-surface-variant: #F5F5F5;
                --md-text-primary: rgba(0, 0, 0, 0.87); 
                --md-text-secondary: rgba(0, 0, 0, 0.6);
                --md-text-hint: rgba(0, 0, 0, 0.38);
                --md-divider: rgba(0, 0, 0, 0.12); 
                --md-overlay: rgba(103, 80, 164, 0.05);
                --md-error: #B3261E;
                --md-outline: #79747E;
                /* Material Design 3 elevation system */
                --elevation-1: 0px 1px 3px 1px rgba(0,0,0,0.15), 0px 1px 2px 0px rgba(0,0,0,0.30); 
                --elevation-2: 0px 2px 6px 2px rgba(0,0,0,0.15), 0px 1px 2px 0px rgba(0,0,0,0.30); 
                --elevation-3: 0px 4px 8px 3px rgba(0,0,0,0.15), 0px 1px 3px 0px rgba(0,0,0,0.30);
                --elevation-4: 0px 6px 10px 4px rgba(0,0,0,0.15), 0px 2px 3px 0px rgba(0,0,0,0.30);
                --elevation-5: 0px 8px 12px 6px rgba(0,0,0,0.15), 0px 4px 4px 0px rgba(0,0,0,0.30);
                /* Material Design spacing system */
                --spacing-1: 8px; 
                --spacing-2: 16px; 
                --spacing-3: 24px;
                --spacing-4: 32px;
                --spacing-5: 40px;
                /* Material Design shape system */
                --border-radius-small: 4px;
                --border-radius-medium: 8px;
                --border-radius-large: 16px;
                /* Material Design motion system */
                --transition-standard: 0.3s cubic-bezier(0.2, 0.0, 0, 1.0);
                --transition-emphasized: 0.5s cubic-bezier(0.2, 0.0, 0, 1.0);
            }
            * { margin: 0; padding: 0; box-sizing: border-box; }
            body { 
                background-color: var(--md-background); 
                font-family: ${isRTL ? "'Amiri', serif" : "'Roboto', sans-serif"}; 
                direction: ${isRTL ? "rtl" : "ltr"}; 
                text-align: ${isRTL ? "right" : "left"}; 
                color: var(--md-text-primary); 
                line-height: 1.5; 
                padding: var(--spacing-2); 
                min-height: 100vh; 
                display: flex; 
                align-items: center; 
                justify-content: center;
                font-size: 16px;
                font-weight: 400;
            }
            .max-w-2xl { 
                max-width: 800px; 
                width: 100%; 
                margin: 0 auto; 
                background-color: var(--md-surface); 
                border-radius: var(--border-radius-medium); 
                box-shadow: var(--elevation-2); 
                padding: var(--spacing-3); 
                transition: box-shadow var(--transition-standard), transform var(--transition-standard);
                animation: slideUp var(--transition-emphasized);
                position: relative;
                overflow: hidden;
            }
            .max-w-2xl:hover { 
                box-shadow: var(--elevation-4); 
                transform: translateY(-2px);
            }
            .max-w-2xl::after {
                content: '';
                position: absolute;
                top: 0;
                left: 0;
                width: 100%;
                height: 4px;
                background: linear-gradient(90deg, var(--md-primary) 0%, var(--md-primary-dark) 100%);
            }
            h1, h2 { 
                font-weight: 400; 
                margin-bottom: var(--spacing-2); 
                line-height: 1.2; 
                color: var(--md-primary-dark);
                letter-spacing: 0.0125em;
            }
            h1 { 
                font-size: 32px; /* Material Design headline large */
                margin-top: var(--spacing-2);
                font-weight: 400;
                line-height: 40px;
            }
            h2 { 
                font-size: 24px; /* Material Design headline medium */
                font-weight: 400;
                line-height: 32px;
                padding-bottom: var(--spacing-1); 
                border-bottom: 1px solid var(--md-divider);
                color: var(--md-text-primary);
                margin-top: var(--spacing-4);
            }
            .mb-6 { 
                ${isRTL ? "text-align: left;" : "text-align: right;"} 
                color: var(--md-text-secondary); 
                font-size: 14px; 
                margin-bottom: var(--spacing-3); 
            }
            .mb-6 a { 
                color: var(--md-primary); 
                text-decoration: none; 
                border-radius: var(--border-radius); 
                transition: background-color var(--transition-standard);
                padding: 4px 8px;
                margin: -4px -8px;
            }
            .mb-6 a:hover { background-color: var(--md-primary-light); }
            .mb-6 a:focus {
                outline: none;
                box-shadow: 0 0 0 2px var(--md-primary-light);
            }
            ul { 
                list-style: none; 
                padding: 0; 
                ${isRTL ? "margin-right: 0;" : "margin-left: 0;"} 
                margin-bottom: var(--spacing-3);
            }
            li { 
                margin-bottom: var(--spacing-2); 
                padding: var(--spacing-2) var(--spacing-3); 
                background-color: var(--md-surface); 
                border-radius: var(--border-radius-medium);
                border: 1px solid var(--md-outline);
                transition: all var(--transition-standard);
                box-shadow: var(--elevation-1);
            }
            li:hover { 
                background-color: var(--md-secondary-light); 
                box-shadow: var(--elevation-2);
                transform: translateY(-2px);
                border-color: var(--md-primary);
            }
            li strong { 
                font-weight: 500; 
                font-size: 18px; /* Material Design title medium */
                line-height: 24px;
                letter-spacing: 0.0125em;
                margin-bottom: var(--spacing-1); 
                color: var(--md-primary-dark); 
                display: block;
                position: relative;
                padding-${isRTL ? "right" : "left"}: var(--spacing-2);
            }
            li strong::before {
                content: '';
                position: absolute;
                ${isRTL ? "right" : "left"}: 0;
                top: 50%;
                transform: translateY(-50%);
                width: 4px;
                height: 18px;
                background-color: var(--md-primary);
                border-radius: var(--border-radius-small);
            }
            ol { 
                list-style-type: decimal; 
                ${isRTL ? "margin-right: var(--spacing-3);" : "margin-left: var(--spacing-3);"} 
                margin-top: var(--spacing-1);
            }
            ol li { 
                margin-bottom: 0.3rem; 
                padding: 4px 0; 
                background-color: transparent; 
                border-left: none; 
                border-right: none;
                box-shadow: none;
            }
            ol li:hover { 
                background-color: transparent; 
                transform: none;
                box-shadow: none;
            }
            .bullet-content ol { margin-top: 0.3rem; margin-bottom: 0.3rem; }
            .footer { 
                text-align: center; 
                margin-top: var(--spacing-4); 
                padding: var(--spacing-3);
                color: var(--md-text-secondary);
                position: relative;
                font-size: 14px;
                letter-spacing: 0.25px;
                line-height: 20px;
            }
            .footer::before {
                content: '';
                position: absolute;
                top: 0;
                left: 20%;
                right: 20%;
                height: 1px;
                background: linear-gradient(90deg, transparent, var(--md-divider) 50%, transparent);
            }
            .text-gray-500 { color: var(--md-text-secondary); }
            .text-gray-600 { color: var(--md-text-secondary); }
            .text-gray-800 { color: var(--md-primary-dark); }
            .rounded-xl, .rounded-2xl { border-radius: var(--border-radius); }
            .image-container { 
                position: relative; 
                margin: var(--spacing-3) 0; 
                border-radius: var(--border-radius-large); 
                overflow: hidden; 
                box-shadow: var(--elevation-2);
                transition: all var(--transition-emphasized);
                transform-origin: center center;
            }
            .image-container:hover { 
                transform: scale(1.02); 
                box-shadow: var(--elevation-4);
            }
            .image-container img { 
                width: 100%; 
                display: block;
                transition: transform var(--transition-emphasized);
            }
            .my-6 { margin-top: var(--spacing-2); margin-bottom: var(--spacing-2); }
            .border-gray-200 { background-color: var(--md-divider); height: 1px; }
            .bullet-content { 
                color: var(--md-text-secondary); 
                line-height: 1.6;
                font-weight: 400;
            }
            /* Material Design state layer effect */
            li, .image-container, a {
                position: relative;
                overflow: hidden;
            }
            li::after, .image-container::after {
                content: '';
                position: absolute;
                top: 50%;
                left: 50%;
                width: 10px;
                height: 10px;
                background: var(--md-primary);
                opacity: 0;
                border-radius: 100%;
                transform: scale(1) translate(-50%, -50%);
                transition: opacity 0.5s cubic-bezier(0.4, 0.0, 0.2, 1), transform 0.5s cubic-bezier(0.4, 0.0, 0.2, 1);
            }
            li:active::after, .image-container:active::after {
                opacity: 0.12; /* Material Design state layer opacity */
                transform: scale(80) translate(-50%, -50%);
                transition: transform 0.5s cubic-bezier(0.4, 0.0, 0.2, 1);
            }
            /* Accessibility */
            a:focus, button:focus {
                outline: 2px solid var(--md-primary);
                outline-offset: 2px;
            }
            @keyframes slideUp { from { opacity: 0; transform: translateY(20px); } to { opacity: 1; transform: translateY(0); } }
            @media (max-width: 600px) { 
                body { padding: var(--spacing-1); } 
                .max-w-2xl { 
                    padding: var(--spacing-2);
                    border-radius: var(--border-radius-small);
                }
                h1 { 
                    font-size: 24px; 
                    line-height: 32px;
                }
                h2 { 
                    font-size: 20px; 
                    line-height: 28px;
                }
                li { 
                    padding: var(--spacing-2);
                    margin-bottom: var(--spacing-1);
                }
                .image-container {
                    border-radius: var(--border-radius-medium);
                }
            }
            
            /* Dark mode support */
            @media (prefers-color-scheme: dark) {
                :root {
                    --md-background: #1C1B1F;
                    --md-surface: #242329;
                    --md-surface-variant: #2E2D33;
                    --md-primary: #D0BCFF;
                    --md-primary-dark: #CCC2DC;
                    --md-accent: #CCC2DC;
                    --md-text-primary: rgba(255, 255, 255, 0.87);
                    --md-text-secondary: rgba(255, 255, 255, 0.6);
                    --md-text-hint: rgba(255, 255, 255, 0.38);
                    --md-divider: rgba(255, 255, 255, 0.12);
                    --md-outline: #938F99;
                }
                
                li:hover {
                    background-color: rgba(208, 188, 255, 0.08);
                }
                
                li strong::before {
                    background-color: var(--md-primary);
                }
            }
            @media print {
                body { background: white; }
                .max-w-2xl { box-shadow: none; }
                .max-w-2xl::after { display: none; }
                .image-container { box-shadow: none; }
                li { box-shadow: none; background: none; border-left-color: #999; }
                li strong::before { background-color: #999; }
                h1, h2, .text-gray-800 { color: black; }
                .text-gray-500, .text-gray-600, .bullet-content { color: #333; }
            }
        `,
        templates: {
            bodyWrapper: (content) =>
                `<div class="max-w-2xl w-full bg-white rounded-2xl shadow-lg p-6">${content}</div>`,
            header: (text, isRTL) =>
                `<div class="mb-6 ${isRTL ? "text-left" : "text-right"} text-gray-500 text-sm">${text} <a href="https://github.com/Hassan-ach" class="underline hover:text-gray-700">Bagi</a></div>`,
            title: (title) =>
                `<h1 class="text-4xl text-gray-800 mb-4">${title}</h1>`,
            image: (url) =>
                `<div class="image-container"><img src="${url}" alt="Video thumbnail" /></div>`,
            sectionContainer: (title, list) => `<div>${title}${list}</div>`,
            sectionTitle: (title) =>
                `<h2 class="text-2xl text-gray-800 mb-4">${title}</h2>`,
            bulletList: (items) => `<ul class="text-gray-600">${items}</ul>`,
            bulletItem: (bold, text) =>
                `<li><strong>${bold}</strong><br /><div class="bullet-content">${text}</div></li>`,
            footer: () =>
                `<div class="footer"><hr class="my-6 border-gray-200" /><p>Made with ❤️ by Bagi</p></div>`,
        },
    },
};

// --- PUBLIC API --------------------------------------------------------------

/**
 * Generates a well-formatted HTML document containing the video summary.
 * This is the default, clean theme.
 *
 * @param {string} title - The title of the YouTube video.
 * @param {string} imageUrl - URL to the video thumbnail image.
 * @param {Array} sections - Array of sections with topics and questions/answers.
 * @param {string} [lang='en'] - Language code.
 * @returns {string} Complete HTML document as a string.
 */
export function htmlGenerator(title, imageUrl, sections, lang = "en") {
    return _generateHtmlForTheme("default", title, imageUrl, sections, lang);
}

/** Generates HTML with a Neomorphism theme. */
export function htmlGeneratorNeomorphism(
    title,
    imageUrl,
    sections,
    lang = "en",
) {
    return _generateHtmlForTheme(
        "neomorphism",
        title,
        imageUrl,
        sections,
        lang,
    );
}

/** Generates HTML with a Glassmorphism theme. */
export function htmlGeneratorGlassmorphism(
    title,
    imageUrl,
    sections,
    lang = "en",
) {
    return _generateHtmlForTheme(
        "glassmorphism",
        title,
        imageUrl,
        sections,
        lang,
    );
}

/** Generates HTML with a Retro/Y2K theme. */
export function htmlGeneratorRetroY2K(title, imageUrl, sections, lang = "en") {
    return _generateHtmlForTheme("retroY2K", title, imageUrl, sections, lang);
}

/** Generates HTML with a Hacker/Terminal theme. */
export function htmlGeneratorHacker(title, imageUrl, sections, lang = "en") {
    return _generateHtmlForTheme("hacker", title, imageUrl, sections, lang);
}

/** Generates HTML with a modern Typography-focused theme. */
export function htmlGeneratorTypography(
    title,
    imageUrl,
    sections,
    lang = "en",
) {
    return _generateHtmlForTheme("typography", title, imageUrl, sections, lang);
}

/** Generates HTML with a Maximalist theme. */
export function htmlGeneratorMaximalist(
    title,
    imageUrl,
    sections,
    lang = "en",
) {
    return _generateHtmlForTheme("maximalist", title, imageUrl, sections, lang);
}

/** Generates HTML with a Brutalist theme. */
export function htmlGeneratorBrutalist(title, imageUrl, sections, lang = "en") {
    return _generateHtmlForTheme("brutalist", title, imageUrl, sections, lang);
}

/** Generates HTML with a Flat UI theme. */
export function htmlGeneratorFlat(title, imageUrl, sections, lang = "en") {
    return _generateHtmlForTheme("flat", title, imageUrl, sections, lang);
}

/** Generates HTML with a Minimalist theme. */
export function htmlGeneratorMinimalist(
    title,
    imageUrl,
    sections,
    lang = "en",
) {
    return _generateHtmlForTheme("minimalist", title, imageUrl, sections, lang);
}

/** Generates HTML with a Material Design theme. */
export function htmlGeneratorMaterial(title, imageUrl, sections, lang = "en") {
    return _generateHtmlForTheme("material", title, imageUrl, sections, lang);
}
